services:
  - type: web
    name: alishasaldaevabaza-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: BOT_TOKEN
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: YOOKASSA_SHOP_ID
        sync: false
      - key: YOOKASSA_SECRET_KEY
        sync: false
      - key: CHANNEL_ID
        sync: false
      - key: ADMIN_CHAT_IDS
        sync: false
      - key: RENDER_URL
        sync: false
      - key: RETURN_URL
        sync: false
      - key: PORT
        value: 10000
      - key: PAYMENT_GROUP_ID
        sync: false
    healthCheckPath: /health